spring:

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
minio:
  endpoint: http://192.168.58.135:80
  accessKey: minioadmin
  secretKey: minioadmin
#  bucketName: myvideo

